# Generated by Django 3.2.11 on 2022-02-07 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_id', models.CharField(max_length=100, null=True)),
                ('tenant_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=100)),
                ('enabled', models.BooleanField()),
                ('credit_rating', models.PositiveIntegerField()),
                ('credit_limit', models.PositiveIntegerField()),
                ('credit_balance', models.PositiveIntegerField()),
                ('credit_outstanding', models.PositiveIntegerField()),
                ('distributor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreditManagement.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='ledger_action_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=100)),
                ('tenant_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('distributor_id', models.ManyToManyField(null=True, related_name='Store', to='CreditManagement.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='ledger_transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.BigIntegerField()),
                ('credit_balance', models.PositiveIntegerField()),
                ('credit_outstanding', models.PositiveIntegerField()),
                ('ledger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreditManagement.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='ledger_actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_value', models.PositiveIntegerField()),
                ('current_value', models.PositiveIntegerField()),
                ('action_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreditManagement.ledger_action_types')),
                ('ledger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreditManagement.ledger')),
            ],
        ),
        migrations.AddField(
            model_name='ledger',
            name='store_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CreditManagement.store'),
        ),
    ]
