# Generated by Django 3.2.11 on 2022-02-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreditManagement', '0002_alter_ledger_store_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ledger',
            unique_together={('distributor_id', 'store_id')},
        ),
    ]
