# Generated by Django 3.2.11 on 2022-02-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditManagement', '0003_alter_ledger_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='store_id',
            field=models.CharField(max_length=100),
        ),
    ]
