# Generated by Django 3.0.7 on 2022-02-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditManagement', '0005_auto_20220209_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='credit_rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ledger_actions',
            name='current_value',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ledger_actions',
            name='prev_value',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ledger_transactions',
            name='transaction_amount',
            field=models.PositiveIntegerField(),
        ),
    ]
